# Generated by Django 5.0.3 on 2024-04-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_enterproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_date',
            new_name='date',
        ),
    ]
